[scripts][cmake] Add conan support
vlad-ostas/peanuts pull request #14
Opened 2024-09-08 22:15 UTC by Akumanory

Добавил поддерку пакетного менеджера в проект
Добавил пару скриптов что бы ручками это не прописывать
По хорошему надо бы что бы кто то из вас проверил у себя нормально ли отрабатывают скрипты на чистой системе
Но профиль системы там пока только для линукс чуть позже добавлю для винды

2024-09-16 01:40 UTC, vlad-ostas requested changes
Круто, потому что это работает. Особенно со скриптами оч удобно (для начала). Нужно исправить мелочи по оформлению файлов и пару настроек

2024-09-16 01:40 UTC, vlad-ostas commented on conanfile.py
> +from conan import ConanFile
если это возможно, то лучше переместить этот файл в scripts/

2024-09-16 01:40 UTC, vlad-ostas commented on scripts/conan_build.sh
> +conan install ../conanfile.py -sbuild_type=Debug -of=../conan_modules/debug --profile=./configs/default_conan_profile --build=missing -c tools.system.package_manager:mode=install -c tools.system.pack
нужно сделать переносы, чтобы не было длинного однострочника

2024-09-16 01:40 UTC, vlad-ostas commented on scripts/build_w_tests.sh
> +cmake -B ../build/Debug -S .. -D CMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-12 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="./conan_modules/debug/conan_toolch
длинный однострочник, сделать переносы

2024-09-16 01:40 UTC, vlad-ostas commented on scripts/configs/default_conan_profile
> +compiler=gcc
надо заменить на:
- компилятор clang
- стандарт c++20

2024-09-16 01:43 UTC, vlad-ostas commented on conanfile.py
> +from conan import ConanFile
Я почитал, что в контексте конана это не скрипт как таковой, так что можно оставить

2024-09-17 13:42 UTC, vlad-ostas requested changes
При установке на чистый комп (с только установленным конаном) не подтягивается конан-профиль

2024-09-17 13:42 UTC, vlad-ostas commented on scripts/conan_build.sh
> +
Добавить строку с:
```sh
conan profile detect —force
```

2024-09-17 13:43 UTC, vlad-ostas commented on scripts/conan_build.sh
> +
—force нужен для перезаписи профиля, если такой уже существует

2024-09-19 18:29 UTC, Akumanory commented on scripts/conan_build.sh
> +
блин странно
я же в скрипте видимо не совсем правильно путь до файла указал в котором профиль находится

2024-09-19 18:30 UTC, Akumanory commented on scripts/conan_build.sh
> +
`--profile=./configs/default_conan_profile`
в этой строчке похоже обосрался

2024-09-19 18:32 UTC, Akumanory commented on scripts/configs/default_conan_profile
> +compiler=gcc
не тут все впорядке, зто конфиг для пакетов конана, я смотрел по зависимостям они как раз собираются с такими параметрами
на сайте конана это можно глянуть

2024-09-19 18:33 UTC, Akumanory commented on scripts/build_w_tests.sh
> +cmake -B ../build/Debug -S .. -D CMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-12 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="./conan_modules/debug/conan_toolch
а как там в баше переносы делать то?

2024-09-19 22:17 UTC, vlad-ostas commented on scripts/build_w_tests.sh
> +cmake -B ../build/Debug -S .. -D CMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-12 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLCHAIN_FILE="./conan_modules/debug/conan_toolch
на конце строки бэкслеш `\`

2024-09-19 23:04 UTC, vlad-ostas commented on scripts/configs/default_conan_profile
> +compiler=gcc
так а мб пусть и зависимости билдятся с такими же вводными, как и сам движок

2024-09-20 00:39 UTC, vlad-ostas commented on scripts/conan_build.sh
> +
возможно, потому что я сейчас перепроверил (удалил у себя default профиль), и выдало вот это:
> ./conan_build.sh 
ERROR: The default build profile '/home/ostas/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'

В `conan install --help` можно посмотреть синтаксис команды

2024-09-20 18:19 UTC, Akumanory commented on scripts/conan_build.sh
> +
Ну вот тут написанно что для билда он дефолтный профиль хочет, видимо нужно добавлять спецификацию 
Там просто есть профиль host и build 
Я пока хз чем они отличаются

2024-09-20 18:22 UTC, Akumanory commented on scripts/conan_build.sh
> +
> Добавить строку с:
> 
> ```shell
> conan profile detect —force
> ```

Так точно нельзя делать, у нас тогда всегда на разных машинах будут разные профили, так что нет

2024-09-20 19:49 UTC, vlad-ostas commented on scripts/conan_build.sh
> +
Да, согласен. Я не так понял профили

2024-09-22 18:46 UTC, Akumanory commented on scripts/configs/default_conan_profile
> +compiler=gcc
В результате разобрались примерно с профайлами
 есть host и build profiles 
 host  - профиль машины в которой будет запускаться либа
 build - профиль если мы используем --build=missing для локальной сборки зависимостей
 следовательно оставляем host как определилось в системе, а build прописываем как минимально необходимое для сборки зависимостей на сайте конана

2024-10-06 17:46 UTC, closed without merging